# Generated by Django 3.2 on 2022-09-12 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('classe', models.CharField(choices=[('99', 'any'), ('0', 'Mahdhara'), ('1', '1AF'), ('2', '2AF'), ('3', '3AF'), ('4', '4AF'), ('5', '5AF'), ('6', '6AF'), ('7', '1AS'), ('8', '2AS'), ('9', '3AS'), ('10', '4AS'), ('11', '5AS'), ('12', '6AS'), ('13', '7AS')], max_length=30, null=True, verbose_name='classe')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, unique=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='teacher name')),
                ('classe', models.CharField(choices=[('99', 'any'), ('0', 'Mahdhara'), ('1', '1AF'), ('2', '2AF'), ('3', '3AF'), ('4', '4AF'), ('5', '5AF'), ('6', '6AF'), ('7', '1AS'), ('8', '2AS'), ('9', '3AS'), ('10', '4AS'), ('11', '5AS'), ('12', '6AS'), ('13', '7AS')], max_length=30, null=True, verbose_name='classe')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, unique=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.CharField(choices=[('0', 'All'), ('1', 'Maths'), ('2', 'Physique Chimie'), ('3', 'Sciences Naturelles'), ('4', 'Arabe'), ('5', 'Français'), ('6', 'Anglais'), ('7', 'Mahdhara'), ('8', 'Autre')], max_length=20, primary_key=True, serialize=False, verbose_name='subject')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOrder',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.order')),
                ('classe', models.CharField(choices=[('99', 'any'), ('0', 'Mahdhara'), ('1', '1AF'), ('2', '2AF'), ('3', '3AF'), ('4', '4AF'), ('5', '5AF'), ('6', '6AF'), ('7', '1AS'), ('8', '2AS'), ('9', '3AS'), ('10', '4AS'), ('11', '5AS'), ('12', '6AS'), ('13', '7AS')], max_length=30, null=True, verbose_name='classe')),
            ],
        ),
        migrations.CreateModel(
            name='LessonOrder',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.order')),
                ('hours', models.IntegerField(blank=True, default=2, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=200, null=True)),
                ('students_count', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
