# Generated by Django 3.2 on 2022-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classe',
            field=models.CharField(choices=[('Tout', 'Tout'), ('Mahdhara', 'Mahdhara'), ('1AF', '1AF'), ('2AF', '2AF'), ('3AF', '3AF'), ('4AF', '4AF'), ('5AF', '5AF'), ('6AF', '6AF'), ('1AS', '1AS'), ('2AS', '2AS'), ('3AS', '3AS'), ('4AS', '4AS'), ('5AS', '5AS'), ('6AS', '6AS'), ('7AS', '7AS')], max_length=30, null=True, verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(choices=[('Tout', 'Tout'), ('Mahdhara', 'Mahdhara'), ('1AF', '1AF'), ('2AF', '2AF'), ('3AF', '3AF'), ('4AF', '4AF'), ('5AF', '5AF'), ('6AF', '6AF'), ('1AS', '1AS'), ('2AS', '2AS'), ('3AS', '3AS'), ('4AS', '4AS'), ('5AS', '5AS'), ('6AS', '6AS'), ('7AS', '7AS')], max_length=25, primary_key=True, serialize=False, verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='document',
            name='classe',
            field=models.CharField(choices=[('Tout', 'Tout'), ('Mahdhara', 'Mahdhara'), ('1AF', '1AF'), ('2AF', '2AF'), ('3AF', '3AF'), ('4AF', '4AF'), ('5AF', '5AF'), ('6AF', '6AF'), ('1AS', '1AS'), ('2AS', '2AS'), ('3AS', '3AS'), ('4AS', '4AS'), ('5AS', '5AS'), ('6AS', '6AS'), ('7AS', '7AS')], max_length=30, null=True, verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Tout', 'All'), ('Mathématiques', 'Mathematics'), ('Physique Chimie', 'Physics and Chemistry'), ('Sciences Naturelles', 'Natural Sciences'), ('Arabe', 'Arabic'), ('Français', 'French'), ('Anglais', 'English'), ('Mahdhara', 'Mahdhara'), ('Autre', 'Other')], max_length=25, primary_key=True, serialize=False, verbose_name='subject'),
        ),
    ]
