# Generated by Django 3.2 on 2022-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('A', 'Literature'), ('C', 'Mathématiques'), ('D', 'Sciences_Naturelles'), ('O', 'Sciences_Religieuses'), ('T', 'Technique')], max_length=50, primary_key=True, serialize=False, verbose_name='specialty'),
        ),
    ]
