# Generated by Django 3.2 on 2022-09-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220914_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorder',
            name='document',
            field=models.OneToOneField(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.document'),
        ),
    ]
