# Generated by Django 3.2 on 2022-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20221016_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=254, upload_to='./document_files', verbose_name='document_file'),
        ),
    ]
