# Generated by Django 3.2 on 2022-09-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220922_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentorder',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=254, null=True, upload_to='./document_files', verbose_name='document_file'),
        ),
        migrations.AddField(
            model_name='documentorder',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.subject'),
        ),
        migrations.AddField(
            model_name='documentorder',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
    ]
