# Generated by Django 3.2 on 2022-10-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_document_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonorder',
            name='classes',
            field=models.ManyToManyField(blank=True, to='backend.Classe'),
        ),
    ]
