# Generated by Django 3.2 on 2022-10-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_lessonorder_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='title',
        ),
    ]
