# Generated by Django 3.2 on 2022-10-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_transaction_validated'),
        ('backend', '0009_auto_20221017_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonorder',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.teacher'),
        ),
    ]
