# Generated by Django 3.2 on 2022-10-22 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_transaction_status'),
        ('backend', '0010_lessonorder_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('lesson_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.lessonorder')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.student')),
            ],
        ),
    ]
