# Generated by Django 3.2 on 2022-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_review_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('0', 'Autre'), ('A', 'Literature'), ('C', 'Mathématiques'), ('D', 'Sciences_Naturelles'), ('O', 'Sciences_Religieuses'), ('T', 'Technique')], max_length=50, primary_key=True, serialize=False, verbose_name='specialty'),
        ),
    ]
