# Generated by Django 3.2 on 2022-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='diploma',
            field=models.FileField(blank=True, default=None, max_length=254, null=True, upload_to='./teachers_diplomes', verbose_name='diploma'),
        ),
    ]
