# Generated by Django 3.2 on 2022-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
