# Generated by Django 3.2 on 2022-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_disponibility'),
        ('user_app', '0002_alter_teacher_disponibilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='disponibilities',
        ),
        migrations.AddField(
            model_name='teacher',
            name='disponibilities',
            field=models.ManyToManyField(blank=True, to='backend.Disponibility'),
        ),
    ]
