# Generated by Django 3.2 on 2022-09-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_teacher_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='hourly_wage',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='hourly wage'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='introduction',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='introduction'),
        ),
    ]
