# Generated by Django 3.2 on 2022-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20220922_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.CharField(choices=[('99', 'any'), ('0', 'Mahdhara'), ('1AF', '1AF'), ('2AF', '2AF'), ('3AF', '3AF'), ('4AF', '4AF'), ('5AF', '5AF'), ('6AF', '6AF'), ('1AS', '1AS'), ('2AS', '2AS'), ('3AS', '3AS'), ('4AS', '4AS'), ('5AS', '5AS'), ('6AS', '6AS'), ('7AS', '7AS')], max_length=30, null=True, verbose_name='classe'),
        ),
    ]
