# Generated by Django 3.2 on 2022-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_student_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='validated_account',
            field=models.BooleanField(default=False, verbose_name='validated_account'),
        ),
    ]
