# Generated by Django 3.2 on 2022-09-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_teacher_validated_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='validated_account',
        ),
        migrations.AddField(
            model_name='teacher',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
