# Generated by Django 3.2 on 2022-08-22 17:40

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_account_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='transaction date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='account number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.CharField(choices=[('99', 'any'), ('0', 'Mahdara'), ('1', '1AF'), ('2', '2AF'), ('3', '3AF'), ('4', '4AF'), ('5', '5AF'), ('6', '6AF'), ('7', '1AS'), ('8', '2AS'), ('9', '3AS'), ('10', '4AS'), ('11', '5AS'), ('12', '6AS'), ('13', '7AS')], max_length=30, null=True, verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(blank=True, choices=[('A', 'Literature'), ('C', 'Mathématiques'), ('D', 'Sciences_Naturelles'), ('O', 'Sciences_Religieuses'), ('T', 'Technique')], max_length=30, null=True, verbose_name='specialty'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avg_rating',
            field=models.IntegerField(default=0, verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='diploma',
            field=models.FileField(blank=True, default=None, max_length=254, null=True, upload_to=None, verbose_name='diploma'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='disponibilities',
            field=models.JSONField(null=True, verbose_name='disponibilities'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hourly_wage',
            field=models.PositiveIntegerField(default=1000, verbose_name='hourly wage'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='introduction',
            field=models.CharField(max_length=1000, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name='subjects'), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_MRU',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account_number',
            field=models.UUIDField(verbose_name='destination account number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone'),
        ),
        migrations.CreateModel(
            name='ChargingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_MRU', models.IntegerField(verbose_name='amount')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone')),
                ('txn_id', models.CharField(blank=True, max_length=50, verbose_name='TXN ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='transaction date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_transaction', to='user_app.account')),
            ],
        ),
    ]
