# Generated by Django 3.2 on 2022-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20220822_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingtransaction',
            name='wallet',
            field=models.CharField(choices=[('bankily', 'Bankily'), ('masrvi', 'Masrvi'), ('sedad', 'Sedad')], default='bankily', max_length=30, verbose_name='Wallet'),
            preserve_default=False,
        ),
    ]
