# Generated by Django 3.2 on 2022-08-24 16:09

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_chargingtransaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_account_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(default=user_app.models.Transaction.default_platform_account, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_account', to='user_app.account'),
        ),
    ]
