# Generated by Django 3.2 on 2022-09-09 13:33

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20220824_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingtransaction',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charging_transaction', to='user_app.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.OneToOneField(default=user_app.models.Transaction.default_platform_account, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_account', to='user_app.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sending_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='user_app.account'),
        ),
    ]
