# Generated by Django 3.2 on 2022-09-09 14:19

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20220909_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.OneToOneField(blank=True, default=user_app.models.Transaction.default_platform_account, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_account', to='user_app.account'),
        ),
    ]
